services:
  - type: web
    name: text-extractor-webhook
    env: docker
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: RENDER_APP_URL
        sync: false
    startCommand: "gunicorn bot:flask_app --bind 0.0.0.0:$PORT"
