services:
  - type: web
    name: text-extractor-bot-free
    env: docker
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TESSERACT_CMD # This is the new variable
        value: /usr/bin/tesseract
