services:
  - type: web
    name: text-extractor-final
    env: docker
    # הנתיב לבדיקת "בריאות" השרת. חיוני כדי להשאיר את השירות ער.
    healthCheckPath: /
    # משתני סביבה. ודא שהוספת אותם גם בממשק של Render.
    envVars:
      - key: BOT_TOKEN
        generateValue: true # Render יצור עבורך שדה ריק למלא
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
